Exception occurred in preexec_fn.